# Generated by Django 4.2.1 on 2025-02-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='歌手名称')),
                ('introduction', models.TextField(blank=True, verbose_name='歌手简介')),
                ('popularity', models.IntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'db_table': 'music_artist',
            },
        ),
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='风格名称')),
            ],
            options={
                'verbose_name': '音乐风格',
                'verbose_name_plural': '音乐风格',
                'db_table': 'music_style',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否是管理员'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_artists', models.TextField(blank=True, help_text='用逗号分隔的歌手名称', verbose_name='喜欢的歌手')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('favorite_styles', models.ManyToManyField(to='app01.musicstyle', verbose_name='喜欢的音乐风格')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='app01.user')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
                'db_table': 'user_preference',
            },
        ),
    ]
